# 🚀 Starship Configuration

format = """
[╭─](bold blue) $os$username$hostname$directory$git_branch$git_status$git_state
[╰─](bold blue) $character
"""

[os]
format = "[$symbol]($style)"
style = "bold blue"
disabled = false

[os.symbols]
Arch = " "

[username]
style_user = "bold cyan"
style_root = "bold red"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "at [$hostname](bold purple) in "
disabled = false

[directory]
style = "bold yellow"
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

[git_branch]
symbol = " "
style = "bold green"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"
