# ==============================================================================
# Calamares — display manager module config for NooreldeanOS
# ==============================================================================
---
displaymanagers:
  - sddm

basicSetup: false

sddm:
  setupAutoLogin: false
