# ==============================================================================
# Calamares — partition module config for NooreldeanOS
# ==============================================================================
---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice: none

defaultFileSystemType: "ext4"

availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
