# ==============================================================================
# Calamares — bootloader module config for NooreldeanOS
# ==============================================================================
---
efiBootLoader: "grub"
kernel: "/vmlinuz-linux-zen"
img: "/initramfs-linux-zen.img"
fallback: "/initramfs-linux-zen-fallback.img"
timeout: 5
kernelLine: ", with NooreldeanOS"
fallbackKernelLine: ", with NooreldeanOS (fallback initramfs)"
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"
installEFIFallback: true
