# ==============================================================================
# Calamares — fstab module config for NooreldeanOS
# ==============================================================================
---
mountOptions:
  default: defaults,noatime
  btrfs: defaults,noatime,compress=zstd,space_cache=v2,discard=async
  ext4: defaults,noatime

ssdExtraMountOptions:
  btrfs: discard=async,ssd
  ext4: discard

crypttabOptions: luks
