# ==============================================================================
# Calamares — locale module config for NooreldeanOS
# ==============================================================================
---
region: "Africa"
zone: "Cairo"

localeGenPath: "/etc/locale.gen"

geoip:
  style: "json"
  url: "https://ipapi.co/json"
  selector: ""
