# ==============================================================================
# Calamares — services-systemd module config for NooreldeanOS
# ==============================================================================
---
services:
  - name: "NetworkManager"
    mandatory: true

  - name: "sddm"
    mandatory: true

  - name: "bluetooth"
    mandatory: false

  - name: "ufw"
    mandatory: false

  - name: "nooreldeanos-gpu-setup"
    mandatory: false

targets:
  - name: "graphical"
    mandatory: true

disable:
  - name: "nooreldeanos-live-setup"
    mandatory: false
